-- Full shagun coin catalogue pulled from shaguncoins.com (gold coin + premium
-- silver coin listing pages, 2026-07-19). manual_price here is a REFERENCE
-- value (their listed price, same weight tier) so the price filter has
-- something to work with — Saurav decided against an automated daily
-- competitor-price scrape (ToS/fragility risk); staff will set the real
-- price directly once demand comes in via the enquiry cart.

insert into corporate_gifting_products (category, name, sort_order, price_mode, image_url, manual_price) values
  ('shagun_coins', '100 mg. GOLD COIN - Lakshmi', 100, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/aqehij8y6itapbwdx6kw', 2287),
  ('shagun_coins', '2 GRAM GOLD COIN SET NEW (1 GRAM x 2 COINS) Birthday', 101, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/f03wwnykwow8bvzlz0kl', 32754),
  ('shagun_coins', '500 mg. GOLD COIN SET (100 mg. x 5 COINS) Tree', 102, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/zp8y8nytbmpt2ttypzyh', 10043),
  ('shagun_coins', '5 GRAM GOLD COIN BIG SIZE 38 MM - WEDDING COUPLE', 103, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/oz8yw1nm1qlaz8fnz0zc', 78795),
  ('shagun_coins', '2 GRAM GOLD COIN SET NEW (1 GRAM x 2 COINS) Anniversary', 104, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/nsdv8utwdt7ayskny0n4', 32754),
  ('shagun_coins', '500 mg. GOLD COINS KIDS - DUCK', 105, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ngkf5ustqvxnctbdtu1w', 10043),
  ('shagun_coins', '500 mg. GOLD COINS KIDS - TEDDY', 106, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/gzobxickjsrdcfy50sx0', 10043),
  ('shagun_coins', '1 GRAM GOLD COIN - Ganesh', 107, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/vu3uhqzzwsxqo6ucch1v', 16377),
  ('shagun_coins', '1 GRAM GOLD COIN - happy wedding', 108, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/znasddnys1g7b6tuxcjc', 16377),
  ('shagun_coins', '1 GRAM. GOLD SPOON KIDS - 22 K', 109, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ihoqsfhurdbsuf3frbpu', 18257),
  ('shagun_coins', '1 GRAM GOLD FIGURINE - RAM LALLA', 110, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/qi764mbnj4h0x0u7dqzb', 20085),
  ('shagun_coins', '1 GRAM GOLD COIN - Peacock', 111, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/fv2vxmyr0da8rp0e4bkb', 16377),
  ('shagun_coins', '100 mg. GOLD COIN - Tree', 112, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/cygfodk6t1klyvzecp8z', 2287),
  ('shagun_coins', '500 mg. GOLD COIN - happy wedding', 113, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ot6as1grtmnusn9ajtqs', 8652),
  ('shagun_coins', '1 GRAM GOLD COIN - shagun', 114, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/at99gnvrd6wjiwsxus7z', 16377),
  ('shagun_coins', '500 mg. GOLD COIN - Thankyou', 115, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/bdyau7ur7cn3ojepwsp5', 8652),
  ('shagun_coins', '500 mg. GOLD COINS KIDS - CAR', 116, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/g8gznfcbmwl0qx5xzx90', 10043),
  ('shagun_coins', '500 mg. GOLD COIN - Tirupati', 117, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/tnkc47xkvzgudnyf3dk1', 8652),
  ('shagun_coins', '2 GRAM GOLD COIN SET - KING QUEEN (1 GRAM X 2 COINS)', 118, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/sqb5iyi2qg7n33iupuxj', 32754),
  ('shagun_coins', '500 mg. GOLD COINS KIDS - BOTTLE', 119, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/otlsccwl1nhpiimhk0dn', 10043),
  ('shagun_coins', '200 mg. GOLD COINS - SRIYANTRA', 120, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/f4jsznbksagerqorvidk', 3801),
  ('shagun_coins', '1 GRAM GOLD BAR TREE', 121, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/pioxrl6nr0zcghfk42xb', 16377),
  ('shagun_coins', '100 mg. GOLD COIN - shagun', 122, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/xbtrrfi8pbguvzbycqqk', 2287),
  ('shagun_coins', '1 GRAM GOLD COIN SET NEW (500 mg. x 2 COINS) Birthday', 123, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/j7lhfrumgyyzuixl2ke1', 16995),
  ('shagun_coins', 'SHAGUN LIFAFA - 500 mg. GOLD - Thankyou', 124, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/fybf0sijyltyr6efmwkr', 9116),
  ('shagun_coins', '2 GRAM GOLD COIN SET NEW (1 GRAM x 2 COINS) Tree', 125, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/n9hmohawi0yxyhoak1jb', 32754),
  ('shagun_coins', '10 GRAM GOLD COIN BIG SIZE 50 MM - MAYUR', 126, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/baxdkor3btz9wnh6ebpm', 155736),
  ('shagun_coins', '1 GRAM GOLD COIN - Thankyou', 127, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ekgn57gevbye5wse3syd', 16377),
  ('shagun_coins', '1 GRAM GOLD FIGURINE - LAXMI', 128, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/wralzguz08xuks0ic7dl', 20085),
  ('shagun_coins', '500 mg. GOLD COIN - Anniversary', 129, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/szdddnzpsq1n2sn89xwp', 8652),
  ('shagun_coins', '500 mg. GOLD COIN - Diwali', 130, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/vmmwssmdpzryaotxdnrz', 8652),
  ('shagun_coins', '2 GRAM GOLD COIN SET NEW (500 MG. x 4 COINS) Best wishes', 131, 'manual', null, 33990),
  ('shagun_coins', '1 GRAM GOLD COIN SET (100 mg. x 10 COINS) Tree', 132, 'manual', null, 16377),

  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - tree printed', 200, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/k0fmgr9fgt3pgi4grfsl', 1981),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - hanuman ji', 201, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/tmbhzp20oedmwrf9fien', 3150),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - shiv pariwar', 202, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/zc9q5f3hwx10epevuk51', 3150),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - shiv pariwar printed', 203, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/zh43fqw0k7pe6qs5gcew', 1981),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - birthday printed', 204, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/e4mtx7f4f2ldmwjgdrgx', 1981),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - LAXMI', 205, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/uqmbgrarf1izrukjrmwa', 505),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - Laxmi ganesh', 206, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/miru3j0jklm488csfyyh', 1981),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - best wishes', 207, 'manual', null, 3150),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - laxmi printed', 208, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/xgjvarve7rfzfyyzfhga', 1981),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - wedding printed', 209, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/urcwofc7h3xg5gdkwvua', 3150),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - wedding printed', 210, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/prxhdzujtzhgix0bgxvr', 1981),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - THANKYOU', 211, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/r9qkr2w8bhodowrqsymg', 505),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - Radha krishna printed', 212, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/o6lijhgxx9usaioesyxq', 1981),
  ('shagun_coins', '2.5 GRAM SILVER COIN PREMIUM - SHAGUN', 213, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/jqhgmej3y1tnw82dmf2w', 946),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - ganesh printed', 214, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/b4zwxszpmx6ej1hyckgd', 3150),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - BIRTHDAY', 215, 'manual', null, 505),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - tree printed', 216, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/wgluprcm20hyznffo3dk', 3150),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - laxmi printed', 217, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ow0sb9ae9j71nqiowwfh', 3150),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - KING', 218, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/tm8tx4pf85djzhhphfia', 505),
  ('shagun_coins', '2.5 GRAM SILVER COIN PREMIUM - LAXMI GANESH', 219, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/s39rtshns4aiwrdmpofa', 946),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - RAKSHA BANDHAN', 220, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/l5yjubhcnyxwksmnwqxu', 505),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - TIRUPATI', 221, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/skm6nb7eyxgpgw04kpnc', 505),
  ('shagun_coins', '1 GRAM SILVER COIN PREMIUM - WEDDING BLUE', 222, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ovgsp9j3jlga8fz3fp3h', 505),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - Anniversary printed', 223, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/dys8bcnkvse8wfywckvo', 3150),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - Namokar mantra printed', 224, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/ovzq2zteckjoo7js5vaa', 1981),
  ('shagun_coins', '2.5 GRAM SILVER COIN PREMIUM - MAYUR', 225, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/dculzp7hch32qlemyxzq', 946),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - best wishes printed', 226, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/awgcjmvc3fsgs8nve7kh', 1981),
  ('shagun_coins', '2.5 GRAM SILVER COIN PREMIUM - ROSE', 227, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/fdjkdne29ocvrxviofxe', 946),
  ('shagun_coins', '10 GRAM SILVER COIN BIG SIZE PREMIUM - 60MM - GOLDEN TEMPLE', 228, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/xrp5albhyanp0mcxbsgk', 3150),
  ('shagun_coins', '5 GRAM SILVER COIN BIG SIZE PREMIUM - 50MM - Anniversary printed', 229, 'manual', 'https://img.jewelflix.com/indigo-prints4170/products/anrnavvjs4t5ifkudior', 1981)
on conflict do nothing;
